name: Build release artifacts

on:
  release:
    types: [created]

jobs:
  build-windows:
    name: Build Windows exe
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build with PyInstaller
        run: |
          py -3 -m PyInstaller --noconfirm --onefile --windowed even_illumination_app.py
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/even_illumination_app.exe
          asset_name: even_illumination_app-windows.exe
          asset_content_type: application/octet-stream

  build-macos:
    name: Build macOS app
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt pyinstaller
      - name: Build with PyInstaller
        run: |
          python3 -m PyInstaller --noconfirm --onefile --windowed even_illumination_app.py
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/even_illumination_app
          asset_name: even_illumination_app-macos
          asset_content_type: application/octet-stream
